apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch-exporter
  namespace: freeswitch
  labels:
    app: freeswitch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeswitch-exporter
  template:
    metadata:
      labels:
        app: freeswitch-exporter
    spec:
      containers:
      - name: freeswitch-exporter
        image: florentchauveau/freeswitch_exporter:latest
        env:
        - name: FREESWITCH_SERVER
          value: "freeswitch-service"
        - name: FREESWITCH_PORT
          value: "8021"
        - name: FREESWITCH_PASSWORD
          value: "ClueCon"
        ports:
        - containerPort: 9282
          name: metrics
