apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
  namespace: freeswitch
spec:
  type: NodePort
  selector:
    app: freeswitch
  ports:
  - port: 8021
    targetPort: 8021
    name: esl
  - port: 5060
    targetPort: 5060
    nodePort: 30060
    name: sip-udp
    protocol: UDP
  - port: 5060
    targetPort: 5060
    nodePort: 30060
    name: sip-tcp
    protocol: TCP
